# Streamlit Cloud Secrets Configuration
# Copy this to your Streamlit Cloud app secrets section

[aws]
access_key_id = "YOUR_AWS_ACCESS_KEY_ID"
secret_access_key = "YOUR_AWS_SECRET_ACCESS_KEY"
region = "ca-central-1"

[bedrock]
model_id = "anthropic.claude-3-sonnet-20240229-v1:0"
guardrail_id = "wym574vww1er"
guardrail_version = "2"

[app]
environment = "production"
debug = false

# Optional: Database configurations if needed
[database]
# Add any database connection strings if required
chroma_db_path = "./chroma_db"

# Optional: API keys for external services
[external_apis]
# Add any additional API keys if needed